# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
url: "https://tobashi.github.io"
baseurl: "/"
permalink: /:year/:month/:day/:title/

# Site meta
title: Tobashi
description: Description — among other things.

author: Tobias

repository: "tobashi/tobashi.github.io"

socnet_users:
  - github_username: tobashi

# Build settings
markdown: kramdown
